/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchNameRouteImport } from './routes/match-name'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsSessionIdRouteImport } from './routes/results/$sessionId'
import { Route as QuizSessionIdRouteImport } from './routes/quiz/$sessionId'

const MatchNameRoute = MatchNameRouteImport.update({
  id: '/match-name',
  path: '/match-name',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdRoute = QuizSessionIdRouteImport.update({
  id: '/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/match-name': typeof MatchNameRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/match-name': typeof MatchNameRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/match-name': typeof MatchNameRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/match-name'
    | '/quiz/$sessionId'
    | '/results/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/match-name'
    | '/quiz/$sessionId'
    | '/results/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/match-name'
    | '/quiz/$sessionId'
    | '/results/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MatchNameRoute: typeof MatchNameRoute
  QuizSessionIdRoute: typeof QuizSessionIdRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/match-name': {
      id: '/match-name'
      path: '/match-name'
      fullPath: '/match-name'
      preLoaderRoute: typeof MatchNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId': {
      id: '/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof QuizSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MatchNameRoute: MatchNameRoute,
  QuizSessionIdRoute: QuizSessionIdRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
